### PR TITLE
Adding the CWL (Common Workflos Language) description for the tool

### PR DESCRIPTION
**Pull request by mattions**
Tracking the CWL on the repo. Using this to bring it on the SBG Platform.
Note: this is based on the other branch, so the docker image use already the entrypoint.

### CODE REVIEW

**Comment by Chris7** [comment]
Hey @mattions, could you let us know what this is being used for? I know Marc would love to get more info on how this is being used (especially for a grant for adding new features to mirge!)

**Comment by mattions** [comment]
Sure, The Common Workflow Language is a way to standardize how to launch bioinformatics softwares.

It's an Open Specification, driven by the community http://www.commonwl.org/ . The repo on github: https://github.com/common-workflow-language/common-workflow-language 

Having it in json format, and pinning the docker image, let's you replicate a bioinformatics analysis.

It's quite new technology.

Disclaimer: I work for Seven Bridges, and I wrapped miRge so we can offer it as a tool on the platform, but I think having the cwl in the repo will be best practise in the future

**Comment by Chris7** [comment]
Thanks @mattions. How does this handle changes to the api? The CWL would have to be updated in sync with the perl scripts. I think the CWL needs to be copied to the docker file as well, otherwise the CWL specs that are listed here and the current CLI for the version of miRge in docker can be out of sync. 

I think launching with docker is a great approach for SB and helps a great deal in keeping workflows sane and reproducible. It's a hard problem (I have my own project on data science reproducibility -- https://github.com/wooey/Wooey)

**Comment by mattions** [comment]
Hi @Chris7 , the CWL only wraps the commandline of miRge, so it needs to be changed and update when the commandline interace is changed. It also record the version of the tool, so when a new miRge is released, the new version should be written in the CWL.

If you do not want to edit the Json by hand, you can use the Editor that you find on sevenbridges platform. (You just need a user, and it is free to make one).

Cheers!

**Pull request merged**
